// Contract parity: the app's offline A* must produce exactly the routes the server would
// (fire-backend/contracts/fixtures/route_cases.json, generated by scripts/make_route_cases.py).
import 'dart:convert';
import 'dart:io';

import 'package:fire_evac/shared/graph.dart';
import 'package:fire_evac/shared/offline_routing.dart';
import 'package:flutter_test/flutter_test.dart';

const fixtures = '../fire-backend/contracts/fixtures';

BuildingGraph load(String name) => BuildingGraph.fromJson(jsonDecode(File('$fixtures/$name.json').readAsStringSync()) as Map<String, dynamic>);

void main() {
  final available = Directory(fixtures).existsSync();

  group('offline A* matches the server planner', () {
    if (!available) {
      test('fixtures not checked out next to the app', () {}, skip: 'needs ../fire-backend');
      return;
    }
    final cases = jsonDecode(File('$fixtures/route_cases.json').readAsStringSync()) as List;
    final graphs = <String, BuildingGraph>{};
    for (final raw in cases) {
      final c = raw as Map<String, dynamic>;
      test('${c['fixture']} from ${c['start']} fire=${c['fire']} stairs=${c['stairs_ok']}', () {
        final g = graphs.putIfAbsent(c['fixture'] as String, () => load(c['fixture'] as String));
        final explicit = {for (final k in c['fire'] as List) g.byKey(k as String).id: 'fire'};
        final hazards = expandHazards(g, explicit);
        final r = planOffline(g, g.byKey(c['start'] as String).id, hazards, stairsOk: c['stairs_ok'] as bool);
        if (c['expected_path'] == null) {
          expect(r, isNull);
          return;
        }
        expect(r, isNotNull);
        expect([for (final n in r!.path) g.nodes[n]!.key], c['expected_path']);
        expect(r.cost, closeTo((c['expected_cost'] as num).toDouble(), 1e-6));
        expect(r.goalType, c['expected_goal_type']);
      });
    }
  });

  group('positioning (paper eq. 1, Alg. 3)', () {
    test('eq. 1 reference point and 10*eta dB per decade', () {
      expect(estimateDistance(-40, -40, 2.7), closeTo(1.0, 1e-9));
      expect(estimateDistance(-67, -40, 2.7), closeTo(10.0, 1e-9));
    });

    test('triangulation picks the right floor and a nearby node', () {
      if (!available) return;
      final g = load('block_b_tower');
      // strong readings from floor 2 routers, weak bleed-through from floor 1
      final fix = triangulate(g, {'b0:00:00:00:02:01': -48, 'b0:00:00:00:02:03': -55, 'b0:00:00:00:02:02': -70, 'b0:00:00:00:01:01': -80});
      expect(fix, isNotNull);
      expect(fix!.level, 2);
      expect(g.nodes[fix.nodeId]!.level, 2);
    });
  });
}
