"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 19:32:38.820936
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('societies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('join_code', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('societies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_societies_join_code'), ['join_code'], unique=True)

    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.Enum('LIVE', 'SIMULATION', name='buildingmode', native_enum=False, length=16), nullable=False),
    sa.Column('floor_height_m', sa.Float(), nullable=False),
    sa.Column('graph_version', sa.Integer(), nullable=False),
    sa.Column('hazard_version', sa.Integer(), nullable=False),
    sa.Column('footprint', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buildings_society_id'), ['society_id'], unique=False)

    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('width_m', sa.Float(), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=False),
    sa.Column('plan_image', sa.String(length=255), nullable=True),
    sa.Column('scale_px_per_m', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'level')
    )
    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_floors_building_id'), ['building_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'EVACUATING', 'ALL_CLEAR', 'CLOSED', name='incidentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('is_simulation', sa.Boolean(), nullable=False),
    sa.Column('trigger', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_building_id'), ['building_id'], unique=False)

    op.create_table('access_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('bssid', sa.String(length=17), nullable=False),
    sa.Column('ssid', sa.String(length=64), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('p_ref', sa.Float(), nullable=False),
    sa.Column('eta', sa.Float(), nullable=False),
    sa.Column('calibrated', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'bssid')
    )
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_points_building_id'), ['building_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_building_id'), ['building_id'], unique=False)
        batch_op.create_index('ix_events_incident_ts', ['incident_id', 'ts'], unique=False)

    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('ROOM', 'CORRIDOR', 'STAIR', 'LIFT', 'EXIT', 'REFUGE', 'ASSEMBLY', name='nodetype', native_enum=False, length=16), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('exit_flow_per_min', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'key')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodes_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodes_floor_id'), ['floor_id'], unique=False)

    op.create_table('position_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_logs_building_id'), ['building_id'], unique=False)
        batch_op.create_index('ix_position_logs_device_ts', ['device_id', 'ts'], unique=False)

    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('a_id', sa.Integer(), nullable=False),
    sa.Column('b_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('DOOR', 'CORRIDOR', 'STAIR', 'LIFT', 'OUTDOOR', name='edgekind', native_enum=False, length=16), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('width_m', sa.Float(), nullable=False),
    sa.Column('accessible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['a_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['b_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edges_building_id'), ['building_id'], unique=False)

    op.create_table('fingerprint_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('readings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fingerprint_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fingerprint_samples_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fingerprint_samples_node_id'), ['node_id'], unique=False)

    op.create_table('node_hazards',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('NONE', 'RISK', 'SMOKE', 'FIRE', name='hazardlevel', native_enum=False, length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id')
    )
    with op.batch_alter_table('node_hazards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_hazards_building_id'), ['building_id'], unique=False)

    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('SMOKE', 'TEMPERATURE', 'FLAME', 'MULTI', 'ALARM_PANEL', name='sensortype', native_enum=False, length=16), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('last_reading', sa.JSON(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensors_building_id'), ['building_id'], unique=False)

    op.create_table('signage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signage_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signage_token'), ['token'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('RESIDENT', 'SURVEYOR', 'RESCUER', 'SOCIETY_ADMIN', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='userstatus', native_enum=False, length=16), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('flat', sa.String(length=32), nullable=True),
    sa.Column('home_node_id', sa.Integer(), nullable=True),
    sa.Column('stairs_ok', sa.Boolean(), nullable=False),
    sa.Column('mobility_notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_society_id'), ['society_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('incident_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UNKNOWN', 'EVACUATING', 'SAFE', 'NEEDS_HELP', name='participantstatus', native_enum=False, length=16), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('safe_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_exit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'device_id')
    )
    with op.batch_alter_table('incident_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_participants_incident_id'), ['incident_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('smoke', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('flame', sa.Boolean(), nullable=True),
    sa.Column('alarm', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.create_index('ix_sensor_readings_sensor_ts', ['sensor_id', 'ts'], unique=False)

    op.create_table('sos_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sos_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sos_requests_building_id'), ['building_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sos_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sos_requests_building_id'))

    op.drop_table('sos_requests')
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_sensor_readings_sensor_ts')

    op.drop_table('sensor_readings')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('incident_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_participants_incident_id'))

    op.drop_table('incident_participants')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))

    op.drop_table('devices')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_society_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('signage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signage_token'))
        batch_op.drop_index(batch_op.f('ix_signage_building_id'))

    op.drop_table('signage')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensors_building_id'))

    op.drop_table('sensors')
    with op.batch_alter_table('node_hazards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_hazards_building_id'))

    op.drop_table('node_hazards')
    with op.batch_alter_table('fingerprint_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fingerprint_samples_node_id'))
        batch_op.drop_index(batch_op.f('ix_fingerprint_samples_building_id'))

    op.drop_table('fingerprint_samples')
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edges_building_id'))

    op.drop_table('edges')
    with op.batch_alter_table('position_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_position_logs_device_ts')
        batch_op.drop_index(batch_op.f('ix_position_logs_building_id'))

    op.drop_table('position_logs')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_floor_id'))
        batch_op.drop_index(batch_op.f('ix_nodes_building_id'))

    op.drop_table('nodes')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_incident_ts')
        batch_op.drop_index(batch_op.f('ix_events_building_id'))

    op.drop_table('events')
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_points_building_id'))

    op.drop_table('access_points')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_building_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_floors_building_id'))

    op.drop_table('floors')
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buildings_society_id'))

    op.drop_table('buildings')
    with op.batch_alter_table('societies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_societies_join_code'))

    op.drop_table('societies')
    # ### end Alembic commands ###
